// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	model "github.com/anxmukul/todo/model"
	mock  "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *Controller) Create(_a0 string, _a1 string) (*model.ToDo, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *model.ToDo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.ToDo, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.ToDo); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ToDo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByTitle provides a mock function with given fields: _a0
func (_m *Controller) DeleteByTitle(_a0 string) (*model.ToDo, error) {
	ret := _m.Called(_a0)

	var r0 *model.ToDo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.ToDo, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *model.ToDo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ToDo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchById provides a mock function with given fields: _a0
func (_m *Controller) SearchById(_a0 int64) (*model.ToDo, error) {
	ret := _m.Called(_a0)

	var r0 *model.ToDo
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*model.ToDo, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int64) *model.ToDo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ToDo)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchByTitle provides a mock function with given fields: _a0
func (_m *Controller) SearchByTitle(_a0 string) (*[]model.ToDo, error) {
	ret := _m.Called(_a0)

	var r0 *[]model.ToDo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*[]model.ToDo, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *[]model.ToDo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.ToDo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
