// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	view "github.com/anxmukul/todo/view"
	mock "github.com/stretchr/testify/mock"
)

// TodoDisplayer is an autogenerated mock type for the TodoDisplayer type
type TodoDisplayer struct {
	mock.Mock
}

// ShowManyTodo provides a mock function with given fields: _a0
func (_m *TodoDisplayer) ShowManyTodo(_a0 *[]view.Todo) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*[]view.Todo) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShowTodo provides a mock function with given fields: _a0, _a1, _a2
func (_m *TodoDisplayer) ShowTodo(_a0 int64, _a1 string, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTodoDisplayer creates a new instance of TodoDisplayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoDisplayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoDisplayer {
	mock := &TodoDisplayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
